Class Level
Class Barrier
Class Bird
Class Background 
Class StartScreen    
Class Animation
Class Score
Class GameoverScreen 
Class Image 
Class Sound 
Class Pipeline
Class Building
Class Postition
Class Coordinate
Class Controller 
Class Player
Class Screen    
Class FlappyGame
Class Skin


FlappyGame "1"*--"*"Level
FlappyGame"1"*--"1"Player
Background"1"*--"*"Animation
Player "1" o--"1" Controller
Level "1"*--"1"Bird
Level"1"*--"*"Barrier
Level"1"*--"*"Background

Level "1" *-- "1" Score
Level"1"*-- "2"Screen

GameoverScreen--|>Screen
StartScreen--|>Screen

Bird "1" o-- "1" Score
Bird "1" *-- "*"Animation
Bird "1"*--"1" Postition

Barrier<|-- Pipeline
Barrier<|--Building
Barrier "*"*-- "*"Image
Barrier "1"*--"1" Postition

Postition"1"*--"2"Coordinate


Controller "1" o--"1" Bird

Animation"1" *-- "*" Image
Animation "1" *-- "*" Sound

Skin--|> Image

Score"1" o-- "1" GameoverScreen
